server:
  port: 8071
spring:
  application:
    name: nacos-consumer

  cloud:
    nacos:
      discovery:
        server-addr: 47.105.206.45:8848
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
service-url:
  nacos-server: http://nacos-service
