server:
  port: 8031

spring:
  application:
    name: zuul-proxy
  cloud:
    nacos:
      discovery:
        server-addr: 47.105.206.45:8848
management:
  endpoints:
    web:
      exposure:
        include: 'routes'
zuul:
  host:
    connect-timeout-millis: 150000
    socket-timeout-millis: 600000
